use std::fs;
use std::path::PathBuf;

fn workspace_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .map(PathBuf::from)
        .unwrap_or_else(|| panic!("failed to derive workspace root"))
}

#[test]
fn openapi_snapshot_contains_new_control_domains() {
    let root = workspace_root();
    let openapi = fs::read_to_string(root.join("openapi/control-plane-v1.yaml"))
        .unwrap_or_else(|error| panic!("failed to read OpenAPI contract: {error}"));

    for required_path in [
        "/healthz",
        "/readyz",
        "/metrics",
        "/runtime/topology",
        "/runtime/participants/tombstone",
        "/runtime/participants/tombstone-history",
        "/runtime/participants/tombstone-history/aggregated",
        "/netsec/policies",
        "/netsec/private-networks/{private_network_id}/subnets",
        "/netsec/private-networks/{private_network_id}/route-tables",
        "/netsec/private-networks/{private_network_id}/route-tables/{route_table_id}/routes",
        "/netsec/private-networks/{private_network_id}/next-hops",
        "/netsec/private-networks/{private_network_id}/service-connect-attachments",
        "/netsec/private-networks/{private_network_id}/nat-gateways",
        "/netsec/private-networks/{private_network_id}/transit-attachments",
        "/netsec/private-networks/{private_network_id}/vpn-connections",
        "/netsec/private-networks/{private_network_id}/peerings",
        "/netsec/service-identities",
        "/control/deployments",
        "/control/shard-placements",
        "/container",
        "/container/node-pools",
        "/container/node-pools/{node_pool_id}",
        "/container/clusters",
        "/container/clusters/{cluster_id}",
        "/container/workloads",
        "/container/workloads/{workload_id}",
        "/container/reconciliations",
        "/container/reconcile",
        "/container/outbox",
        "/container/summary",
        "/scheduler/nodes",
        "/scheduler/placements",
        "/identity/summary",
        "/identity/credential-lifecycle",
        "/identity/users",
        "/identity/users/{user_id}",
        "/identity/users/{user_id}/suspend",
        "/identity/users/{user_id}/reactivate",
        "/identity/sessions",
        "/identity/api-keys",
        "/identity/api-keys/{api_key_id}/rotate",
        "/identity/api-keys/{api_key_id}/revoke",
        "/identity/users/bulk",
        "/identity/workload-identities",
        "/identity/workload-identities/{workload_identity_id}/rotate",
        "/identity/workload-identities/{workload_identity_id}/revoke",
        "/identity/outbox",
        "/billing/summary",
        "/billing/support-entitlements",
        "/billing/budgets",
        "/billing/budget-burn",
        "/billing/budget-notifications",
        "/billing/owner-summaries",
        "/billing/provider-sync",
        "/billing/provider-sync/{sync_id}/deliver",
        "/storage/volumes/{volume_id}/snapshot-policy",
        "/storage/volumes/{volume_id}/recovery-point",
        "/storage/volumes/{volume_id}/recovery-history",
        "/storage/volumes/{volume_id}/restore-actions",
        "/storage/restore-actions/{action_id}",
        "/storage/storage-classes",
        "/storage/durability-tiers",
        "/storage/buckets",
        "/storage/volumes",
        "/ingress/routes",
        "/ingress/routes/{route_id}",
        "/ingress/routes/{route_id}/health-report",
        "/ingress/routes/{route_id}/circuit-event",
        "/ingress/evaluate",
        "/ingress/flow-audit",
        "/ingress/flow-audit/summary",
        "/data/databases",
        "/data/databases/{database_id}",
        "/data/databases/{database_id}/backups",
        "/data/databases/{database_id}/restore",
        "/data/databases/{database_id}/failover",
        "/data/databases/{database_id}/maintenance",
        "/data/databases/{database_id}/migrations",
        "/data/databases/{database_id}/exports",
        "/data/databases/imports",
        "/data/backups",
        "/data/backups/{backup_id}/storage-lineage",
        "/data/restores",
        "/data/restores/{restore_id}/storage-lineage",
        "/data/failovers",
        "/data/exports",
        "/data/imports",
        "/data/migrations",
        "/data/migrations/{migration_id}",
        "/data/migrations/{migration_id}/start",
        "/data/migrations/{migration_id}/complete",
        "/data/migrations/{migration_id}/fail",
        "/data/caches/{cache_id}/exports",
        "/data/caches/imports",
        "/data/queues/{queue_id}/exports",
        "/data/queues/imports",
        "/stream",
        "/stream/summary",
        "/stream/streams",
        "/stream/streams/{stream_id}",
        "/stream/streams/{stream_id}/partitions",
        "/stream/streams/{stream_id}/publish",
        "/stream/streams/{stream_id}/replay",
        "/stream/streams/{stream_id}/lag-summary",
        "/stream/subscriptions",
        "/stream/subscriptions/{subscription_id}",
        "/stream/subscriptions/{subscription_id}/ack",
        "/stream/outbox",
        "/netsec/flow-audit/summary",
        "/dns/zones",
        "/dns/zones/{zone_id}/verify",
        "/dns/records",
        "/dns/publication-intents",
        "/dns/provider-tasks",
        "/dns/provider-tasks/{task_id}/deliver",
        "/mail/domains",
        "/mail/domains/{domain_id}/verify-auth",
        "/mail/dispatch",
        "/mail/dead-letters",
        "/abuse/signals",
        "/abuse/reputation",
        "/abuse/cases",
        "/abuse/quarantines",
        "/abuse/appeals",
        "/abuse/remediation-cases",
        "/abuse/remediation-cases/{id}",
        "/abuse/remediation-cases/{id}/escalate",
        "/abuse/support-cases",
        "/abuse/support-cases/{id}",
        "/abuse/support-cases/{id}/transition",
        "/abuse/evaluate",
        "/abuse/outbox",
        "/notify/messages",
        "/notify/webhook-endpoints",
        "/notify/webhook-endpoints/{id}/rotate-secret",
        "/notify/templates",
        "/notify/preferences",
        "/notify/alert-routes",
        "/notify/alerts/trigger",
        "/notify/summary",
        "/notify/messages/{id}/history",
        "/notify/messages/{id}/acknowledge",
        "/notify/messages/{id}/snooze",
        "/notify/messages/{id}/escalate",
        "/notify/messages/{id}/deliver",
        "/notify/messages/{id}/retry",
        "/notify/dispatch",
        "/notify/dead-letters",
        "/notify/dead-letters/{id}/replay",
        "/notify/outbox",
        "/observe/fleet-ops-rollups",
        "/secrets/items/{secret_id}/reveal/approvals",
        "/secrets/items/{secret_id}/reveal/leases",
        "/secrets/items/{secret_id}/reveal/grants/{grant_id}",
        "/policy/evaluate",
        "/governance/legal-holds",
        "/governance/retention-evaluate",
        "/governance/audit-integrity",
        "/ha/failover",
        "/ha/evacuation",
        "/ha/failover-preflight",
        "/ha/regional-quorum",
        "/ha/quorum-summary",
        "/lifecycle/migrations/apply",
        "/lifecycle/integrity",
        "/uvm/control/summary",
        "/uvm/templates",
        "/uvm/templates/{id}",
        "/uvm/instances",
        "/uvm/instances/{id}",
        "/uvm/instances/{instance_id}/runtime-sessions",
        "/uvm/instances/{instance_id}/runtime-sessions/{runtime_session_id}",
        "/uvm/instances/{instance_id}/runtime-checkpoints",
        "/uvm/instances/{instance_id}/runtime-checkpoints/{checkpoint_id}",
        "/uvm/snapshots",
        "/uvm/snapshots/{id}",
        "/uvm/migrations",
        "/uvm/migrations/{id}",
        "/uvm/images",
        "/uvm/firmware-bundles",
        "/uvm/guest-profiles",
        "/uvm/overlay-policies",
        "/uvm/node-capabilities",
        "/uvm/device-profiles",
        "/uvm/compatibility-matrix",
        "/uvm/observe",
        "/uvm/perf-attestations",
        "/uvm/failure-reports",
        "/uvm/host-evidence",
        "/uvm/preflight-evidence-artifacts",
        "/uvm/claim-decisions",
        "/uvm/benchmark-campaigns",
        "/uvm/benchmark-campaigns/{id}/summary",
        "/uvm/benchmark-baselines",
        "/uvm/benchmark-results",
        "/uvm/native-claim-status",
        "/uvm/reconciliation",
        "/uvm/runtime/instances",
        "/uvm/runtime/instances/{id}",
        "/uvm/runtime/instances/{id}/heartbeat",
        "/uvm/runtime/instances/{id}/restore",
        "/uvm/runtime/preflight",
        "/uvm/runtime/heartbeats",
        "/uvm/runtime/health",
        "/uvm/runtime/checkpoints",
        "/uvm/runtime/checkpoints/{id}",
        "/uvm/runtime/migrations",
        "/uvm/runtime/migrations/{id}",
        "/uvm/outbox",
        "/uvm/outbox/{id}",
        "/uvm/image-outbox",
        "/uvm/node-outbox",
        "/uvm/node-outbox/{id}",
        "/uvm/observe-outbox",
    ] {
        assert!(
            openapi.contains(required_path),
            "OpenAPI snapshot missing path {required_path}"
        );
    }

    for required_token in [
        "claim: /billing",
        "claim: /notify",
        "claim: /secrets",
        "/identity/summary:\n    get:\n      summary: Summarize users, sessions, API keys, workload identities, and credential lifecycle state",
        "required: [users, sessions, api_keys, workload_identities, credential_lifecycle]",
        "enum: [session, api_key, workload_token, secret_version]",
        "enum: [active, expiring, expired, inactive, revoked, suspended_owner]",
        "source_kind:\n                          type: string\n                          nullable: true\n                          enum: [api_key, workload_token]",
        "required: [id, email, display_name, mfa_enabled, suspended, metadata]",
        "required: [id, user_id, issued_at, expires_at, metadata]",
        "/identity/api-keys/{api_key_id}/rotate:\n    post:\n      summary: Rotate API key secret",
        "/identity/api-keys/{api_key_id}/revoke:\n    post:\n      summary: Revoke API key",
        "required:\n                  [id, user_id, name, version, secret_preview, issued_at, active, metadata, secret]",
        "required: [id, user_id, name, version, secret_preview, issued_at, active, metadata]",
        "required: [id, principal, display_name, audiences, active, credential, metadata]",
        "required: [identity, token]",
        "/identity/workload-identities/{workload_identity_id}/rotate:\n    post:\n      summary: Rotate workload identity token",
        "/identity/workload-identities/{workload_identity_id}/revoke:\n    post:\n      summary: Revoke workload identity",
        "/billing/summary:\n    get:\n      summary: Summarize billing accounts, provider sync state, support entitlements, and budget tracking",
        "/billing/support-entitlements:\n    get:\n      summary: List billing support entitlements",
        "required:\n                    [id, billing_account_id, source_kind, source_plan, support_tier, channels, initial_response_sla_minutes, active, metadata]",
        "source_kind:\n                      type: string\n                      enum: [billing_account, subscription]",
        "support_tier:\n                      type: string\n                      enum: [standard, business, enterprise, custom]",
        "support_entitlement_count:",
        "active_support_entitlement_count:",
        "support_entitlements_linked_to_active_accounts:",
        "support_entitlements_linked_to_active_subscriptions:",
        "support_entitlement_source_totals:",
        "support_tier_totals:",
        "required:\n                        [owner_id, account_count, subscription_count, invoice_count, unsettled_invoice_total_cents, budget_count, budgeted_amount_cents, tracked_burn_cents, budget_notification_count, budgets_at_or_over_cap, support_entitlement_count]",
        "enum: [monthly, quarterly, annual, custom]",
        "enum: [soft, hard]",
        "enum: [threshold_reached, soft_cap_exceeded, hard_cap_blocked]",
        "budget_notification_kind_totals:",
        "threshold_percentage:\n                      type: integer\n                      nullable: true",
        "payload:\n                      type: object\n                      additionalProperties: true",
        "/abuse/remediation-cases:\n    get:\n      summary: List operator remediation cases",
        "/abuse/remediation-cases/{id}:\n    get:\n      summary: Get operator remediation case detail",
        "/abuse/remediation-cases/{id}/escalate:\n    post:\n      summary: Escalate operator remediation case",
        "required:\n                    [id, workflow_id, workflow_steps, tenant_subject, abuse_case_ids, quarantine_ids, change_request_ids, notify_message_ids, rollback_evidence_refs, verification_evidence_refs, evidence_state, sla_target_seconds, sla_state, escalation_state, escalation_count, reason, created_at, updated_at, metadata]",
        "required: [name, index, state, updated_at]",
        "state:\n                            type: string\n                            enum: [pending, active, completed, failed, rolled_back]",
        "evidence_state:\n                      type: string\n                      enum:\n                        [ready, rollback_missing, verification_missing, rollback_and_verification_missing]",
        "sla_state:\n                      type: string\n                      enum: [within_sla, at_risk, breached]",
        "escalation_state:\n                      type: string\n                      enum: [none, queued, escalated]",
        "/abuse/support-cases:\n    get:\n      summary: List operator support cases",
        "/abuse/support-cases/{id}:\n    get:\n      summary: Get operator support case detail",
        "/abuse/support-cases/{id}/transition:\n    post:\n      summary: Transition operator support case",
        "required:\n                    [id, tenant_subject, status, priority, remediation_case_ids, change_request_ids, notify_message_ids, reason, created_at, updated_at, metadata]",
        "required: [tenant_subject, reason]",
        "priority:\n                      type: string\n                      enum: [low, normal, high, critical]",
        "status:\n                  type: string\n                  nullable: true\n                  enum: [open, investigating, waiting_on_tenant, blocked, resolved]",
        "/notify/alert-routes:\n    get:\n      summary: List alert routes",
        "required:\n                    [id, name, min_severity, channel, destination, cooldown_seconds, enabled, metadata]",
        "/notify/alerts/trigger:\n    post:\n      summary: Trigger routed alert notifications",
        "required:\n                  [severity, routed, suppressed_by_cooldown, route_ids, notification_ids]",
        "/notify/summary:\n    get:\n      summary: Summarize webhook, template, preference, alert-route, notification, and dead-letter state",
        "required: [webhook_endpoints, templates, preferences, alert_routes, notifications, dead_letters]",
        "post:\n      summary: Create notification message",
        "template_id:\n                  type: string\n                  nullable: true",
        "template_vars:\n                  type: object\n                  nullable: true\n                  additionalProperties:\n                    type: string",
        "subject_key:\n                  type: string\n                  nullable: true",
        "case_reference:\n                  type: string\n                  nullable: true",
        "locale:\n                  type: string\n                  nullable: true",
        "webhook_endpoint_id:\n                  type: string\n                  nullable: true",
        "max_attempts:\n                  type: integer\n                  nullable: true",
        "deliver_after_seconds:\n                  type: integer\n                  nullable: true",
        "required:\n                    [id, channel, destination, subject, body, locale, state, attempts, max_attempts, escalation_count, signature, created_at, updated_at, history, metadata]",
        "required: [sequence, event, occurred_at, actor, state, attempts]",
        "enum: [queued, suppressed, delivered, failed, dead_lettered, requeued, acknowledged, snoozed, escalated]",
        "case_reference:",
        "acknowledged_at:",
        "acknowledged_by:\n                      type: string\n                      nullable: true",
        "acknowledgement_note:\n                      type: string\n                      nullable: true",
        "snoozed_until:",
        "snoozed_by:\n                      type: string\n                      nullable: true",
        "snooze_reason:\n                      type: string\n                      nullable: true",
        "last_escalated_at:\n                      type: string\n                      format: date-time\n                      nullable: true",
        "last_escalated_by:\n                      type: string\n                      nullable: true",
        "last_escalated_notification_id:",
        "related_notification_id:",
        "/notify/messages/{id}/history:\n    get:\n      summary: Get workflow history for one notification",
        "required: [notification_id, escalation_count, history]",
        "acknowledged_by:\n                    type: string\n                    nullable: true",
        "/notify/messages/{id}/acknowledge:\n    post:\n      summary: Acknowledge delivered notification\n      requestBody:\n        required: true\n        content:\n          application/json:\n            schema:\n              type: object\n              properties:\n                note:\n                  type: string\n                case_reference:\n                  type: string",
        "summary: Acknowledge delivered notification",
        "/notify/messages/{id}/snooze:\n    post:\n      summary: Snooze escalation workflow for one notification\n      requestBody:\n        required: true\n        content:\n          application/json:\n            schema:\n              type: object\n              properties:\n                snooze_seconds:\n                  type: integer\n                reason:\n                  type: string\n                case_reference:\n                  type: string",
        "summary: Snooze escalation workflow for one notification",
        "/notify/messages/{id}/escalate:\n    post:\n      summary: Escalate one notification into a follow-up message\n      requestBody:\n        required: true\n        content:\n          application/json:\n            schema:\n              type: object\n              required: [channel, destination]\n              properties:\n                channel:\n                  type: string\n                destination:\n                  type: string",
        "summary: Escalate one notification into a follow-up message",
        "/notify/outbox:\n    get:\n      summary: List durable notify outbox events",
        "required: [id, topic, payload, created_at, updated_at, state]",
        "/uvm/instances/{instance_id}/runtime-sessions:\n    get:\n      summary: List UVM runtime sessions for one instance",
        "/uvm/instances/{instance_id}/runtime-sessions/{runtime_session_id}:\n    get:\n      summary: Get one UVM runtime session for one instance",
        "/uvm/instances/{instance_id}/runtime-checkpoints:\n    get:\n      summary: List UVM runtime checkpoints for one instance",
        "/uvm/instances/{instance_id}/runtime-checkpoints/{checkpoint_id}:\n    get:\n      summary: Get one UVM runtime checkpoint for one instance",
        "/stream/summary:\n    get:\n      summary: Summarize stream inventory, retained log volume, and subscriber lag",
        "summary: Publish records into one managed stream",
        "summary: Replay retained records from one managed stream",
        "summary: Summarize subscriber lag for one managed stream",
        "summary: Acknowledge one stream subscription offset",
        "required: [stream, touched_partitions, appended_records]",
        "required: [stream_id, after_offset, stream_high_watermark, items]",
        "required: [stream_id, consumer_group]",
        "required: [id, stream_id, partition_index, stream_offset, partition_offset, payload, headers, byte_count, published_at, metadata]",
        "/container/summary:\n    get:\n      summary: Summarize container node-pool capacity, cluster bindings, and workload reconciliation state",
        "summary: Create durable container node pool",
        "summary: Delete one durable container node pool",
        "summary: Create admitted container cluster",
        "summary: Create declared container workload",
        "summary: Reconcile container workloads into durable scheduler-ready records",
        "required:\n                    [id, project_id, name, region, scheduler_pool, min_nodes, desired_nodes, max_nodes, metadata]",
        "required: [project_id, name, region, scheduler_pool, min_nodes, desired_nodes, max_nodes]",
        "required: [project_id, name, node_pool_id]",
        "required: [id, cluster_id, project_id, name, image, desired_replicas, execution_class, metadata]",
        "state:\n                      type: string\n                      enum: [planned, blocked]",
        "node_pool_count:",
        "active_project_count:",
        "node_pool_summaries:",
        "cluster_summaries:",
        "required: [value, count]",
        "cluster_id:\n                          type: string\n                          nullable: true",
        "node_pool_name:\n                          type: string\n                          nullable: true",
        "replayed_records:",
        "retired_records:",
        "blocked_records:",
        "required: [id, topic, payload, created_at, updated_at, state]",
        "/scheduler/nodes:\n    get:\n      summary: List scheduler nodes",
        "required:\n                    [id, region, scheduler_pool, cpu_millis, memory_mb, free_cpu_millis, free_memory_mb, drained, metadata]",
        "/scheduler/placements:\n    get:\n      summary: List scheduler placement decisions",
        "    post:\n      summary: Request placement",
        "required: [region, cpu_millis, memory_mb]",
        "workload_id:\n                  type: string\n                cpu_millis:\n                  type: integer\n                  minimum: 1\n                memory_mb:\n                  type: integer\n                  minimum: 1\n                region:\n                  type: string\n                  nullable: true\n                scheduler_pool:\n                  type: string\n                  nullable: true",
        "required: [workload_id, node_id, score, reason]",
        "/secrets/items/{secret_id}/reveal/approvals:\n    post:\n      summary: Approve one routed secret reveal",
        "/secrets/items/{secret_id}/reveal/leases:\n    post:\n      summary: Issue one lease-backed secret reveal grant",
        "/secrets/items/{secret_id}/reveal/grants/{grant_id}:\n    post:\n      summary: Reveal one secret with an approval or lease-backed grant",
        "grant_kind:\n                    type: string\n                    enum: [approval, lease]",
        "required:\n                  [id, secret_id, grant_kind, reason, granted_by, granted_by_kind, granted_at, reveal_count, metadata]",
        "required: [reason, lease_seconds]",
        "required: [id, name, version, value]",
        "lease_seconds:\n                  type: integer\n                  minimum: 1",
        "last_revealed_at:",
        "last_revealed_by_kind:",
        "/observe/fleet-ops-rollups:\n    get:\n      summary: Summarize fleet operations readiness, incident scope, and backlog health across regions and cells",
        "required:\n                  [state_root, generated_at, ha_readiness, incident_state, backlog_health, regions, cells]",
        "regions_missing_reconciliation:",
        "unreconciled_regions:",
        "attributed_region_incidents:",
        "attributed_cell_incidents:",
        "unattributed_incidents:",
        "reconciliation_available:",
        "takeover_pending:",
        "takeover_acknowledged:",
    ] {
        assert!(
            openapi.contains(required_token),
            "OpenAPI snapshot missing token {required_token}"
        );
    }

    for required_token in [
        "x-uhost-route-surfaces:",
        "claim: /healthz",
        "claim: /readyz",
        "claim: /metrics",
        "claim: /runtime/topology",
        "claim: /runtime/participants/tombstone",
        "claim: /runtime/participants/tombstone-history",
        "claim: /runtime/participants/tombstone-history/aggregated",
        "claim: /identity",
        "claim: /container",
        "claim: /stream",
        "/netsec/service-identities:\n    get:\n      summary: List service identities\n      responses:\n        \"200\":\n          description: Service identity list\n          content:",
        "required: [subject, mtls_cert_fingerprint]",
        "mtls_cert_fingerprint:\n                      type: string\n                    labels:\n                      type: object\n                      additionalProperties:\n                        type: string\n                    allowed_private_networks:\n                      type: array\n                      items:\n                        type: string\n                    enabled:\n                      type: boolean",
        "destination:\n                      type: string\n                    metadata:\n                      type: object\n                      required: [created_at, updated_at, lifecycle, ownership_scope, etag]",
        "subnet_id:\n                      type: string\n                      nullable: true\n                    route_table_ids:\n                      type: array\n                      items:\n                        type: string\n                    metadata:\n                      type: object",
        "routing_mode:\n                      type: string\n                      enum: [static, bgp]",
        "claim: /storage/volumes/{volume_id}/snapshot-policy",
        "claim: /storage/volumes/{volume_id}/recovery-point",
        "claim: /storage/volumes/{volume_id}/recovery-history",
        "claim: /storage/volumes/{volume_id}/restore-actions",
        "claim: /storage/restore-actions/{action_id}",
        "claim: /data/backups/{backup_id}/storage-lineage",
        "claim: /data/restores/{restore_id}/storage-lineage",
        "claim: /uvm/runtime",
        "claim: /uvm/preflight-evidence-artifacts",
        "compatibility_requirement:",
        "evidence:",
        "publication_manifests:",
        "attestations:",
        "enum: [signature, provenance]",
        "host_class:",
        "audit_event_id:",
        "published_at:",
        "compatibility_assessment:",
        "secure_boot_posture:",
        "signer_lineage:",
        "policy_revision:",
        "execution_intent:",
        "runner_sequence_id:",
        "lifecycle_event_id:",
        "last_runner_sequence_id:",
        "last_lifecycle_event_id:",
        "/uvm/control/summary:\n    get:\n      summary: Summarize UVM control-plane resources and effective claim publication state\n      responses:\n        \"200\":\n          description: UVM control summary\n          content:",
        "effective_claim_publication_state:\n                    type: string\n                    nullable: true\n                  failing_workload_classes:\n                    type: array\n                    items:\n                      type: string",
        "portability_assessment:",
        "portability_assessment_source:",
        "enum: [first_placement_lineage, linked_runtime_preflight_lineage, runtime_preflight_fallback, request_fallback, unavailable]",
        "portability_assessment_unavailable_reason:",
        "enum: [authoritative_runtime_lineage_missing_portability_evidence]",
        "/uvm/preflight-evidence-artifacts:\n    get:\n      summary: List UVM runtime-preflight evidence artifacts\n      responses:\n        \"200\":\n          description: Runtime-preflight evidence artifact list\n          content:",
        "host_class_evidence_key:\n                      type: string\n                    evidence_mode:\n                      type: string\n                    claim_tier:\n                      type: string",
        "/uvm/native-claim-status:\n    get:\n      summary: Compute native-indistinguishable claim status\n      responses:\n        \"200\":\n          description: Native claim status\n          content:",
        "responses:\n        \"201\":\n          description: Created\n          content:\n            application/json:\n              schema:\n                type: object\n                properties:\n                  id:\n                    type: string\n                  host_evidence_id:\n                    type: string\n                  highest_claim_tier:\n                    type: string\n                  observed_highest_claim_tier:\n                    type: string\n                  benchmark_claim_tier_ceiling:\n                    type: string\n                  claim_status:\n                    type: string\n                  native_indistinguishable_status:\n                    type: boolean\n                  prohibited_claim_count:\n                    type: integer\n                  missing_required_workload_classes:\n                    type: array\n                    items:\n                      type: string\n                  failing_workload_classes:\n                    type: array\n                    items:\n                      type: string\n                  runtime_session_id:\n                    type: string\n                  runtime_preflight_id:\n                    type: string\n                  portability_assessment:",
        "description: UVM claim-decision annotations may include observed_highest_claim_tier, benchmark_claim_tier_ceiling, claim_tier_demoted_from, benchmark_host_class_evidence_key, benchmark_ready_scenarios, and publication_scope_host_class_evidence_key.",
        "runtime_session_id:\n                    type: string\n                  runtime_preflight_id:\n                    type: string\n                  portability_assessment:\n                    type: object\n                    properties:\n                      supported:\n                        type: boolean\n                      selected_backend:\n                        type: string\n                      blockers:\n                        type: array\n                        items:\n                          type: string\n                  portability_assessment_source:\n                    type: string\n                    enum: [first_placement_lineage, linked_runtime_preflight_lineage, runtime_preflight_fallback, request_fallback, unavailable]\n                  portability_assessment_unavailable_reason:\n                    type: string\n                    enum: [authoritative_runtime_lineage_missing_portability_evidence]",
        "host_evidence_id:\n                    type: string\n                  runtime_session_id:\n                    type: string\n                  runtime_preflight_id:\n                    type: string\n                  portability_assessment:\n                    type: object\n                    properties:\n                      supported:\n                        type: boolean\n                      selected_backend:\n                        type: string\n                      blockers:\n                        type: array\n                        items:\n                          type: string\n                  portability_assessment_source:\n                    type: string\n                    enum: [first_placement_lineage, linked_runtime_preflight_lineage, runtime_preflight_fallback, request_fallback, unavailable]\n                  portability_assessment_unavailable_reason:\n                    type: string\n                    enum: [authoritative_runtime_lineage_missing_portability_evidence]\n                  perf_samples:",
        "observed_highest_claim_tier:\n                    type: string\n                  highest_claim_tier:\n                    type: string\n                  benchmark_claim_tier_ceiling:\n                    type: string\n                  benchmark_ready_scenarios:\n                    type: array\n                    items:\n                      type: string",
        "apple_guest_allowed:\n                  type: boolean\n                execution_intent:\n                  type: object",
        "runtime_preflight_id:",
        "selected_via_fallback:",
        "selection_reason:",
        "requested_reason:",
        "requested_at:",
        "current:",
        "process_role:",
        "region:",
        "cell:",
        "process_state:",
        "owner_role:",
        "service_groups:",
        "service_group_directory:",
        "resolved_registration_ids:",
        "conflict_state:",
        "enum: [no_conflict, multiple_healthy_registrations]",
        "participants:",
        "tombstone_history:",
        "registration_id:",
        "region_id:",
        "cell_id:",
        "participant_kind:",
        "lease_registration_id:",
        "reconciliation:",
        "last_reconciled_at:",
        "stale_since:",
        "cleanup_workflow:",
        "workflow_kind:",
        "enum: [pending_review, preflight_confirmed, tombstone_eligible]",
        "review_observations:",
        "last_observed_stale_at:",
        "preflight_confirmed_at:",
        "route_withdrawal:",
        "source_participant_registration_id:",
        "target_readiness:",
        "target_participant_registration_id:",
        "prepared_at:",
        "rollback:",
        "tombstone_eligible_at:",
        "event_id:",
        "participant_subject_id:",
        "actor_subject:",
        "actor_type:",
        "correlation_id:",
        "tombstoned_at:",
        "published_drain_intent:",
        "degraded_reason:",
        "lease_source:",
        "removed_from_cell_directory:",
        "lease_registration_soft_deleted:",
        "cleanup_workflow_soft_deleted:",
        "required: [items, retention]",
        "next_cursor:",
        "retention:",
        "max_entries:",
        "retained_entries:",
        "pruned_entries:",
        "oldest_retained_tombstoned_at:",
        "oldest_retained_event_id:",
        "relay_evidence:",
        "message_id:",
        "delivery_state:",
        "replay_count:",
        "last_replayed_at:",
        "last_replay_reason:",
        "state:\n                          type: object\n                          required: [readiness, drain_intent, published_drain_intent, lease_source, lease]",
        "readiness:",
        "drain_intent:",
        "published_drain_intent:",
        "degraded_reason:",
        "enum: [lease_stale, lease_expired]",
        "lease_source:",
        "enum: [linked_registration, published_state_fallback]",
        "lease_freshness:",
        "healthy:",
        "freshness:",
        "all_in_one",
        "node_adjacent",
        "method_match: any",
        "method_match: safe",
        "method_match: unsafe",
        "surface: public",
        "surface: operator",
        "surface: tenant",
        "match: exact",
        "match: prefix",
        "request_class: read",
        "request_class: control_read",
        "request_class: mutate",
        "request_class: async_mutate",
        "request_class: operator_read",
        "request_class: operator_mutate",
        "request_class: operator_destructive",
        "x-uhost-surface: public",
        "x-uhost-surface: operator",
        "matched_policy_ids",
        "decisive_policy_ids",
        "rule_evaluations",
        "dns_binding:",
        "security_policy:",
        "private_network:",
        "targets:",
        "failover_group:",
        "drain:",
        "tls_owner:",
        "inspection_profile_id:",
        "private_network_id:",
        "publication_evaluation:",
        "inspection_profile_name:",
        "blocked_countries:",
        "min_waf_score:",
        "max_bot_score:",
        "ddos_mode:",
        "private_network_name:",
        "summary: List service-connect attachments for one private network",
        "summary: Create service-connect attachment for one private network",
        "summary: List NAT gateways for one private network",
        "summary: Create NAT gateway for one private network",
        "summary: List transit attachments for one private network",
        "summary: Create transit attachment for one private network",
        "summary: List VPN connections for one private network",
        "summary: Create VPN connection for one private network",
        "summary: List peering connections for one private network",
        "summary: Create peering connection for one private network",
        "service_identity_subject:",
        "private_route_id:",
        "public_ip:",
        "subnet_id:",
        "route_table_ids:",
        "transit_private_network_id:",
        "transit_tenant_id:",
        "transit_cell:",
        "gateway_address:",
        "remote_cidrs:",
        "routing_mode:",
        "peer_private_network_id:",
        "peer_tenant_id:",
        "peer_cell:",
        "verified:",
        "enum: [public, private]",
        "summary: List storage classes",
        "summary: Create storage class",
        "summary: List durability tiers",
        "summary: Create durability tier",
        "summary: List storage buckets",
        "summary: Create storage bucket",
        "summary: List storage volumes",
        "summary: Create storage volume",
        "supported_resource_kinds:",
        "minimum_replica_count:",
        "failure_domain_scope:",
        "storage_binding:",
        "storage_class_id:",
        "durability_tier_id:",
        "required: [id, database_id, kind, state, snapshot_uri, storage_recovery_point, storage_recovery_point_selection_reason, storage_recovery_point_state_reason]",
        "backup_artifact_manifest:",
        "manifest_object_location:",
        "manifest_sha256:",
        "manifest_size_bytes:",
        "manifest_verification:",
        "observed_sha256:",
        "enum: [verified]",
        "object_location:",
        "size_bytes:",
        "storage_recovery_point_selection_reason:",
        "storage_recovery_point_state_reason:",
        "required: [id, database_id, backup_id, state, storage_restore_source_mode, storage_restore_selected_recovery_point, storage_restore_selection_reason, storage_restore_selected_recovery_point_state_reason]",
        "storage_restore_source_mode:",
        "storage_restore_selected_recovery_point:",
        "storage_restore_backup_correlated_recovery_point:",
        "storage_restore_selection_reason:",
        "storage_restore_selected_recovery_point_state_reason:",
        "summary: Inspect persisted database backup storage lineage",
        "required: [backup_id, storage_volume_id, recovery_point, selection_reason, recovery_point_state_reason]",
        "recovery_point_state_reason:",
        "summary: Create managed database export bundle",
        "required: [id, resource_kind, resource_id, state, requested_by, created_at, artifact_root_uri, manifest_uri, checksum_catalog_uri, signed_manifest, checksum_catalog]",
        "artifact_root_uri:",
        "manifest_uri:",
        "checksum_catalog_uri:",
        "checksum_catalog_checksum:",
        "signing_key_ref:",
        "signature_scheme:",
        "signature:",
        "required: [algorithm, entries, checksum]",
        "required: [artifact_uri, checksum, size_bytes]",
        "summary: Verify managed database import bundle",
        "required: [id, resource_kind, source_resource_id, state, requested_by, created_at, verification_result, signed_manifest, checksum_catalog]",
        "source_resource_id:",
        "target_resource_id:",
        "verification_result:",
        "backup_correlated_storage_lineage",
        "latest_ready_fallback",
        "selected_recovery_point_state_reason:",
        "selected_recovery_point, selection_reason, selected_recovery_point_state_reason]",
        "restore_action_id:",
        "restore_workflow_id:",
        "selected_recovery_point:",
        "backup_correlated_recovery_point:",
        "summary: Create shard placement",
        "binding_scope:",
        "enum: [deployment, replica]",
        "min_distinct_cells:",
        "min_distinct_nodes:",
        "enum: [disabled, cold_standby, warm_standby, active_passive]",
    ] {
        assert!(
            openapi.contains(required_token),
            "OpenAPI snapshot missing token {required_token}"
        );
    }

    for required_token in ["boot_device", "install_media_image_id", "cdrom_image"] {
        assert!(
            openapi.contains(required_token),
            "OpenAPI snapshot missing token {required_token}"
        );
    }
}

#[test]
fn protobuf_snapshot_contains_new_services() {
    let root = workspace_root();
    let proto = fs::read_to_string(root.join("proto/control-plane-v1.proto"))
        .unwrap_or_else(|error| panic!("failed to read protobuf contract: {error}"));

    for service in [
        "enum RouteSurface",
        "enum RouteMethodMatch",
        "ROUTE_METHOD_MATCH_ANY",
        "ROUTE_METHOD_MATCH_SAFE",
        "ROUTE_METHOD_MATCH_UNSAFE",
        "enum RouteRequestClass",
        "ROUTE_REQUEST_CLASS_READ",
        "ROUTE_REQUEST_CLASS_CONTROL_READ",
        "ROUTE_REQUEST_CLASS_MUTATE",
        "ROUTE_REQUEST_CLASS_ASYNC_MUTATE",
        "ROUTE_REQUEST_CLASS_OPERATOR_READ",
        "ROUTE_REQUEST_CLASS_OPERATOR_MUTATE",
        "ROUTE_REQUEST_CLASS_OPERATOR_DESTRUCTIVE",
        "enum RuntimeProcessRole",
        "RUNTIME_PROCESS_ROLE_ALL_IN_ONE",
        "RUNTIME_PROCESS_ROLE_NODE_ADJACENT",
        "enum RuntimeLogicalServiceGroup",
        "enum RuntimeReadiness",
        "enum RuntimeDrainIntent",
        "enum RuntimeLeaseFreshness",
        "enum RuntimeParticipantLeaseSource",
        "enum RuntimeParticipantDegradedReason",
        "enum RuntimeParticipantCleanupStage",
        "RUNTIME_PARTICIPANT_LEASE_SOURCE_LINKED_REGISTRATION",
        "RUNTIME_PARTICIPANT_LEASE_SOURCE_PUBLISHED_STATE_FALLBACK",
        "RUNTIME_PARTICIPANT_DEGRADED_REASON_LEASE_STALE",
        "RUNTIME_PARTICIPANT_DEGRADED_REASON_LEASE_EXPIRED",
        "RUNTIME_PARTICIPANT_CLEANUP_STAGE_PENDING_REVIEW",
        "RUNTIME_PARTICIPANT_CLEANUP_STAGE_PREFLIGHT_CONFIRMED",
        "RUNTIME_PARTICIPANT_CLEANUP_STAGE_TOMBSTONE_ELIGIBLE",
        "message RuntimeLeaseState",
        "message RuntimeProcessState",
        "message RuntimeParticipantState",
        "message RuntimeParticipantCleanupWorkflow",
        "message RuntimeParticipantReconciliation",
        "message RuntimeRegionMembership",
        "message RuntimeCellMembership",
        "message RuntimeParticipantRegistration",
        "message RuntimeParticipantTombstoneHistoryEntry",
        "message ListRuntimeParticipantTombstoneHistoryRequest",
        "message RuntimeParticipantTombstoneHistoryRetention",
        "message ListRuntimeParticipantTombstoneHistoryReply",
        "message RuntimeParticipantTombstoneRelayEvidence",
        "message RuntimeParticipantTombstoneAggregateEntry",
        "message ListRuntimeParticipantTombstoneAggregateHistoryRequest",
        "message ListRuntimeParticipantTombstoneAggregateHistoryReply",
        "message RuntimeServiceGroupOwnership",
        "message RuntimeTopologyReply",
        "message TombstoneRuntimeParticipantRequest",
        "message TombstoneRuntimeParticipantReply",
        "RuntimeProcessRole process_role = 1;",
        "RuntimeProcessRole owner_role = 2;",
        "repeated RuntimeServiceGroupOwnership service_groups = 4;",
        "RuntimeProcessState process_state = 5;",
        "RuntimeRegionMembership region = 6;",
        "RuntimeCellMembership cell = 7;",
        "repeated RuntimeParticipantRegistration participants = 8;",
        "repeated RuntimeParticipantTombstoneHistoryEntry tombstone_history = 9;",
        "repeated RuntimeServiceGroupDirectoryEntry service_group_directory = 10;",
        "message RuntimeServiceGroupDirectoryEntry",
        "message RuntimeServiceGroupRegistrationResolution",
        "enum RuntimeServiceGroupConflictState",
        "RuntimeServiceGroupConflictState conflict_state = 3;",
        "RuntimeLeaseFreshness lease_freshness = 10;",
        "bool healthy = 11;",
        "repeated RuntimeParticipantTombstoneHistoryEntry items = 1;",
        "repeated RuntimeParticipantTombstoneAggregateEntry items = 1;",
        "string next_cursor = 2;",
        "RuntimeParticipantTombstoneHistoryRetention retention = 3;",
        "RuntimeParticipantTombstoneHistoryEntry history = 1;",
        "RuntimeParticipantTombstoneRelayEvidence relay_evidence = 2;",
        "message RuntimeEvacuationRouteWithdrawalArtifact",
        "message RuntimeEvacuationTargetReadinessArtifact",
        "message RuntimeEvacuationRollbackArtifact",
        "RuntimeParticipantState state = 9;",
        "RuntimeParticipantReconciliation reconciliation = 10;",
        "uint32 limit = 1;",
        "string cursor = 2;",
        "string event_id = 3;",
        "string cleanup_workflow_id = 7;",
        "uint32 max_entries = 1;",
        "uint32 retained_entries = 2;",
        "uint32 pruned_entries = 3;",
        "string oldest_retained_tombstoned_at = 4;",
        "string oldest_retained_event_id = 5;",
        "RuntimeParticipantCleanupStage stage = 4;",
        "RuntimeDrainIntent published_drain_intent = 4;",
        "RuntimeParticipantLeaseSource lease_source = 5;",
        "RuntimeParticipantDegradedReason degraded_reason = 6;",
        "uint32 review_observations = 5;",
        "string last_observed_stale_at = 6;",
        "string preflight_confirmed_at = 7;",
        "string tombstone_eligible_at = 8;",
        "RuntimeEvacuationRouteWithdrawalArtifact route_withdrawal = 11;",
        "RuntimeEvacuationTargetReadinessArtifact target_readiness = 12;",
        "RuntimeEvacuationRollbackArtifact rollback = 13;",
        "string source_participant_registration_id = 2;",
        "string target_participant_registration_id = 3;",
        "repeated string service_groups = 4;",
        "string prepared_at = 5;",
        "string participant_subject_id = 8;",
        "string actor_subject = 18;",
        "string actor_type = 19;",
        "string correlation_id = 20;",
        "string message_id = 1;",
        "string delivery_state = 6;",
        "uint32 replay_count = 13;",
        "string last_replayed_at = 14;",
        "string last_replay_reason = 15;",
        "service RuntimeService",
        "rpc GetTopology",
        "rpc ListParticipantTombstoneHistory",
        "rpc ListParticipantTombstoneAggregateHistory",
        "rpc TombstoneParticipant",
        "string tombstoned_at = 4;",
        "bool removed_from_cell_directory = 6;",
        "bool lease_registration_soft_deleted = 7;",
        "bool cleanup_workflow_soft_deleted = 8;",
        "RuntimeDrainIntent published_drain_intent = 25;",
        "RuntimeParticipantDegradedReason degraded_reason = 26;",
        "RuntimeParticipantLeaseSource lease_source = 27;",
        "ROUTE_SURFACE_PUBLIC",
        "ROUTE_SURFACE_TENANT",
        "ROUTE_SURFACE_OPERATOR",
        "ROUTE_SURFACE_INTERNAL",
        "message RouteSurfaceBinding",
        "message RuntimeRouteSurfaceManifest",
        "enum EdgeExposureIntent",
        "EDGE_EXPOSURE_PUBLIC",
        "EDGE_EXPOSURE_PRIVATE",
        "message EdgeDnsBinding",
        "message EdgeSecurityPolicyAttachment",
        "message EdgePrivateNetworkAttachment",
        "message EdgePublicationTarget",
        "message EdgePublication",
        "message IngressRouteDnsBindingEvaluationSnapshot",
        "message IngressRouteSecurityPolicyEvaluationSnapshot",
        "message IngressRoutePrivateNetworkEvaluationSnapshot",
        "message IngressRoutePublicationEvaluationSnapshot",
        "enum PrincipalKind",
        "PRINCIPAL_KIND_WORKLOAD",
        "message PrincipalIdentity",
        "string claim = 2;",
        "string match_kind = 3;",
        "RouteSurface surface = 4;",
        "RouteMethodMatch method_match = 5;",
        "RouteRequestClass request_class = 6;",
        "EdgePublication publication = 6;",
        "IngressRoutePublicationEvaluationSnapshot publication_evaluation = 7;",
        "EdgePrivateNetworkAttachment private_network = 4;",
        "repeated EdgePublicationTarget targets = 5;",
        "string cell = 2;",
        "string region = 3;",
        "string failover_group = 4;",
        "bool drain = 5;",
        "string tls_owner = 6;",
        "bool verified = 3;",
        "string inspection_profile_name = 2;",
        "repeated string blocked_countries = 3;",
        "uint32 min_waf_score = 4;",
        "uint32 max_bot_score = 5;",
        "string private_network_name = 2;",
        "BackupArtifactManifest backup_artifact_manifest = 9;",
        "message BackupArtifactManifest",
        "BackupArtifactVerificationResult manifest_verification = 7;",
        "repeated BackupArtifactDescriptor artifacts = 8;",
        "enum BackupArtifactKind",
        "BACKUP_ARTIFACT_KIND_SNAPSHOT_BUNDLE",
        "enum BackupArtifactVerificationState",
        "BACKUP_ARTIFACT_VERIFICATION_STATE_VERIFIED",
        "message BackupArtifactDescriptor",
        "string object_location = 2;",
        "uint64 size_bytes = 4;",
        "message BackupArtifactVerificationResult",
        "string observed_sha256 = 4;",
        "enum ContainerExecutionClass",
        "CONTAINER_EXECUTION_CLASS_SERVICE",
        "CONTAINER_EXECUTION_CLASS_JOB",
        "enum ContainerWorkloadReconciliationState",
        "CONTAINER_WORKLOAD_RECONCILIATION_STATE_PLANNED",
        "CONTAINER_WORKLOAD_RECONCILIATION_STATE_BLOCKED",
        "message GetContainerServiceSummaryRequest",
        "message CreateContainerNodePoolRequest",
        "message ContainerNodePoolReply",
        "message ListContainerNodePoolsReply",
        "message CreateContainerClusterRequest",
        "message ContainerClusterReply",
        "message CreateContainerWorkloadRequest",
        "message ContainerWorkloadReply",
        "message ContainerWorkloadReconciliationReply",
        "message ContainerNodePoolWorkloadSummaryReply",
        "message ContainerClusterWorkloadSummaryReply",
        "message ContainerServiceSummaryReply",
        "message ContainerReconcileSummaryReply",
        "message ContainerOutboxMessageReply",
        "message DeleteContainerResourceReply",
        "optional string if_match_etag = 2;",
        "optional uint64 record_version = 3;",
        "optional ContainerExecutionClass execution_class = 6;",
        "ContainerWorkloadReconciliationState state = 13;",
        "repeated ContainerNodePoolWorkloadSummaryReply node_pool_summaries = 11;",
        "repeated ContainerClusterWorkloadSummaryReply cluster_summaries = 12;",
        "service ContainerService",
        "rpc GetContainerServiceSummary",
        "rpc ListNodePools",
        "rpc CreateNodePool",
        "rpc GetNodePool",
        "rpc DeleteNodePool",
        "rpc ListClusters",
        "rpc CreateCluster",
        "rpc GetCluster",
        "rpc DeleteCluster",
        "rpc ListWorkloads",
        "rpc CreateWorkload",
        "rpc GetWorkload",
        "rpc DeleteWorkload",
        "rpc ListReconciliations",
        "rpc ReconcileWorkloads",
        "rpc ListOutbox",
        "message CreateSchedulerNodeRequest",
        "message SchedulerNodeReply",
        "string scheduler_pool = 3;",
        "message ListSchedulerNodesRequest {}",
        "message ListSchedulerNodesReply",
        "message RequestSchedulerPlacementRequest",
        "optional string scheduler_pool = 5;",
        "message SchedulerPlacementReply",
        "message ListSchedulerPlacementsRequest {}",
        "message ListSchedulerPlacementsReply",
        "service SchedulerService",
        "rpc ListNodes",
        "rpc CreateNode",
        "rpc ListPlacements",
        "rpc RequestPlacement",
        "message GetFleetOpsRollupsRequest",
        "message FleetOpsScopedIncidentRollupReply",
        "message FleetOpsHaReadinessReply",
        "message FleetOpsIncidentStateReply",
        "message FleetOpsBacklogHealthReply",
        "message RegionFleetOpsHaReadinessReply",
        "message RegionFleetOpsBacklogHealthReply",
        "message RegionFleetOpsRollupReply",
        "message CellFleetOpsHaReadinessReply",
        "message CellFleetOpsBacklogHealthReply",
        "message CellFleetOpsRollupReply",
        "message FleetOpsRollupsReply",
        "service ObserveService",
        "rpc GetFleetOpsRollups",
        "uint32 regions_missing_reconciliation = 4;",
        "uint32 unreconciled_regions = 5;",
        "uint32 attributed_region_incidents = 6;",
        "uint32 attributed_cell_incidents = 7;",
        "uint32 unattributed_incidents = 8;",
        "optional uint64 healthy_votes = 7;",
        "optional uint64 majority_threshold = 8;",
        "uint64 uncommitted_entries = 9;",
        "uint32 takeover_pending = 5;",
        "uint32 takeover_acknowledged = 6;",
        "message CreateWorkloadRequest",
        "message WorkloadReply",
        "message ListWorkloadsReply",
        "message CreateDeploymentRequest",
        "message DeploymentReply",
        "message ListDeploymentsReply",
        "enum ShardPlacementBindingScope",
        "SHARD_PLACEMENT_BINDING_SCOPE_DEPLOYMENT",
        "SHARD_PLACEMENT_BINDING_SCOPE_REPLICA",
        "message ShardPlacementSpreadPolicy",
        "enum ShardPlacementFailoverMode",
        "SHARD_PLACEMENT_FAILOVER_MODE_DISABLED",
        "SHARD_PLACEMENT_FAILOVER_MODE_COLD_STANDBY",
        "SHARD_PLACEMENT_FAILOVER_MODE_WARM_STANDBY",
        "SHARD_PLACEMENT_FAILOVER_MODE_ACTIVE_PASSIVE",
        "message ShardPlacementFailoverRule",
        "message CreateShardPlacementRequest",
        "message ShardPlacementReply",
        "message ListShardPlacementsReply",
        "ShardPlacementBindingScope binding_scope = 2;",
        "optional uint32 replica_ordinal = 3;",
        "optional string node_id = 5;",
        "ShardPlacementSpreadPolicy spread = 6;",
        "ShardPlacementFailoverRule failover = 7;",
        "ShardPlacementBindingScope binding_scope = 3;",
        "optional uint32 replica_ordinal = 4;",
        "optional string node_id = 6;",
        "ResourceMetadata metadata = 9;",
        "service ControlService",
        "rpc ListWorkloads",
        "rpc CreateWorkload",
        "rpc ListDeployments",
        "rpc CreateDeployment",
        "rpc ListShardPlacements",
        "rpc CreateShardPlacement",
        "message CreateWorkloadIdentityRequest",
        "message WorkloadIdentityReply",
        "message IssueWorkloadIdentityReply",
        "rpc IssueWorkloadIdentity",
        "rpc ListWorkloadIdentities",
        "service IngressService",
        "rpc CreateRoute",
        "rpc EvaluateRoute",
        "string private_network_id = 6;",
        "rpc ReportBackendHealth",
        "rpc RecordCircuitEvent",
        "rpc SummarizeFlowAudit",
        "enum StorageResourceKind",
        "STORAGE_RESOURCE_KIND_BUCKET",
        "STORAGE_RESOURCE_KIND_VOLUME",
        "STORAGE_RESOURCE_KIND_DATABASE",
        "enum StorageMedium",
        "STORAGE_MEDIUM_OBJECT",
        "STORAGE_MEDIUM_BLOCK",
        "enum StorageFailureDomainScope",
        "STORAGE_FAILURE_DOMAIN_SCOPE_CELL",
        "STORAGE_FAILURE_DOMAIN_SCOPE_REGION",
        "message StorageBindingReply",
        "message StorageClassReply",
        "message DurabilityTierReply",
        "message ListStorageClassesRequest",
        "message ListStorageClassesReply",
        "message CreateStorageClassRequest",
        "message ListDurabilityTiersRequest",
        "message ListDurabilityTiersReply",
        "message CreateDurabilityTierRequest",
        "message ListBucketsRequest",
        "message CreateBucketRequest",
        "message BucketReply",
        "message ListBucketsReply",
        "message ListVolumesRequest",
        "message CreateVolumeRequest",
        "message VolumeReply",
        "message ListVolumesReply",
        "service DataService",
        "rpc CreateDatabase",
        "rpc CreateBackup",
        "rpc DescribeBackupStorageLineage",
        "rpc RestoreDatabase",
        "rpc DescribeRestoreStorageLineage",
        "rpc FailoverDatabase",
        "rpc SetMaintenance",
        "rpc ExportDatabase",
        "rpc ImportDatabase",
        "rpc ExportCache",
        "rpc ImportCache",
        "rpc ExportQueue",
        "rpc ImportQueue",
        "rpc ListExports",
        "rpc ListImports",
        "rpc CreateMigration",
        "rpc GetMigration",
        "rpc ListMigrations",
        "rpc StartMigration",
        "rpc CompleteMigration",
        "rpc FailMigration",
        "enum RestoreStorageSourceMode",
        "RESTORE_STORAGE_SOURCE_MODE_BACKUP_CORRELATED_STORAGE_LINEAGE",
        "RESTORE_STORAGE_SOURCE_MODE_LATEST_READY_FALLBACK",
        "message BackupStorageRecoveryPoint",
        "message DataRestoreReply",
        "message DataChecksumCatalogEntry",
        "message DataChecksumCatalog",
        "message SignedDataTransferManifest",
        "message DataExportReply",
        "message DataImportReply",
        "message ListDataExportsReply",
        "message ListDataImportsReply",
        "message CreateDataMigrationRequest",
        "message GetDataMigrationRequest",
        "message ListDataMigrationsRequest",
        "message DataMigrationReply",
        "message ListDataMigrationsReply",
        "message StartDataMigrationRequest",
        "message CompleteDataMigrationRequest",
        "message FailDataMigrationRequest",
        "message GetStreamServiceSummaryRequest {}",
        "message StreamServiceSummaryReply",
        "message ListManagedStreamsRequest {}",
        "message CreateManagedStreamRequest",
        "message ManagedStreamReply",
        "message ListManagedStreamsReply",
        "message GetManagedStreamRequest",
        "message StreamPartitionReply",
        "message ListStreamPartitionsRequest",
        "message ListStreamPartitionsReply",
        "message PublishStreamRecordRequest",
        "message PublishStreamRequest",
        "message StreamLogRecordReply",
        "message StreamPublishReply",
        "message GetStreamReplayRequest",
        "message StreamReplayPageReply",
        "message GetStreamLagSummaryRequest",
        "message StreamLagSummaryReply",
        "message ListStreamSubscriptionsRequest",
        "message CreateStreamSubscriptionRequest",
        "message StreamSubscriptionReply",
        "message ListStreamSubscriptionsReply",
        "message GetStreamSubscriptionRequest",
        "message AcknowledgeStreamSubscriptionRequest",
        "message ListStreamOutboxRequest {}",
        "message StreamOutboxMessageReply",
        "message ListStreamOutboxReply",
        "service StreamService",
        "rpc GetStreamServiceSummary",
        "rpc ListStreams",
        "rpc CreateStream",
        "rpc GetStream",
        "rpc ListStreamPartitions",
        "rpc PublishStream",
        "rpc GetStreamReplay",
        "rpc GetStreamLagSummary",
        "rpc ListSubscriptions",
        "rpc CreateSubscription",
        "rpc GetSubscription",
        "rpc AcknowledgeSubscription",
        "rpc ListOutbox",
        "uint64 total_retained_record_bytes = 10;",
        "uint64 latest_partition_offset = 3;",
        "map<string, string> headers = 9;",
        "optional uint64 partition_high_watermark = 5;",
        "uint64 max_lag_messages = 11;",
        "BackupStorageRecoveryPoint storage_recovery_point = 6;",
        "string storage_recovery_point_selection_reason = 7;",
        "string storage_recovery_point_state_reason = 8;",
        "BackupStorageRecoveryPoint storage_restore_selected_recovery_point = 7;",
        "BackupStorageRecoveryPoint storage_restore_backup_correlated_recovery_point = 9;",
        "string storage_restore_selection_reason = 5;",
        "string storage_restore_selected_recovery_point_state_reason = 6;",
        "RestoreStorageSourceMode storage_restore_source_mode = 8;",
        "message DescribeBackupStorageLineageRequest",
        "message BackupStorageLineageInspection",
        "message DescribeRestoreStorageLineageRequest",
        "message RestoreStorageLineageInspection",
        "string storage_class_id = 7;",
        "string durability_tier_id = 8;",
        "StorageBindingReply storage_binding = 8;",
        "StorageBindingReply storage_binding = 4;",
        "StorageBindingReply storage_binding = 5;",
        "BackupStorageRecoveryPoint recovery_point = 3;",
        "string selection_reason = 4;",
        "string recovery_point_state_reason = 5;",
        "string checksum_catalog_checksum = 7;",
        "string signature_scheme = 9;",
        "SignedDataTransferManifest signed_manifest = 12;",
        "DataChecksumCatalog checksum_catalog = 13;",
        "string verification_result = 12;",
        "SignedDataTransferManifest signed_manifest = 13;",
        "DataChecksumCatalog checksum_catalog = 14;",
        "BackupStorageRecoveryPoint selected_recovery_point = 6;",
        "BackupStorageRecoveryPoint backup_correlated_recovery_point = 7;",
        "string selection_reason = 8;",
        "string selected_recovery_point_state_reason = 9;",
        "string storage_class = 7;",
        "string target_storage_class = 7;",
        "string failure_reason = 19;",
        "service StorageService",
        "rpc ListStorageClasses",
        "rpc CreateStorageClass",
        "rpc ListDurabilityTiers",
        "rpc CreateDurabilityTier",
        "rpc ListBuckets",
        "rpc CreateBucket",
        "rpc ListVolumes",
        "rpc CreateVolume",
        "message StorageVolumeScopeRequest",
        "message DescribeVolumeRestoreActionRequest",
        "message VolumeSnapshotPolicyReply",
        "message VolumeRecoveryPointReply",
        "message VolumeRecoveryHistoryEntry",
        "message ListVolumeRecoveryHistoryReply",
        "message CreateVolumeRestoreActionRequest",
        "message VolumeRestoreActionReply",
        "message ListVolumeRestoreActionsReply",
        "rpc DescribeVolumeSnapshotPolicy",
        "rpc DescribeVolumeRecoveryPoint",
        "rpc ListVolumeRecoveryHistory",
        "rpc ListVolumeRestoreActions",
        "rpc CreateVolumeRestoreAction",
        "rpc DescribeVolumeRestoreAction",
        "optional uint64 recovery_point_version = 2;",
        "bool current = 6;",
        "string requested_reason = 11;",
        "string requested_at = 12;",
        "string lifecycle = 15;",
        "service DnsService",
        "message CreateDnsZoneRequest",
        "message VerifyDnsZoneRequest",
        "message DnsZoneReply",
        "message CreateDnsRecordRequest",
        "message DnsRecordReply",
        "enum DnsSteeringMode",
        "DNS_STEERING_MODE_WEIGHTED",
        "DNS_STEERING_MODE_PRIORITY",
        "DNS_STEERING_MODE_GEO",
        "DNS_STEERING_MODE_LATENCY",
        "message DnsAliasHealthCheck",
        "message CreateDnsPublicationAnswerRequest",
        "message DnsPublicationAnswerReply",
        "message CreateDnsPublicationIntentRequest",
        "message DnsPublicationIntentReply",
        "message ListDnsPublicationIntentsReply",
        "message MarkDnsProviderTaskDeliveredRequest",
        "message DnsProviderTaskReply",
        "rpc ListZones",
        "rpc CreateZone",
        "rpc VerifyZone",
        "rpc ListRecords",
        "rpc CreateRecord",
        "rpc ListPublicationIntents",
        "rpc CreatePublicationIntent",
        "rpc ListProviderTasks",
        "rpc MarkProviderTaskDelivered",
        "service NetsecService",
        "message ListNetsecServiceIdentitiesRequest {}",
        "message ListNetsecServiceIdentitiesReply",
        "rpc BulkCreateUsers",
        "rpc ListServiceIdentities",
        "rpc RegisterServiceIdentity",
        "message CreateNetsecServiceConnectAttachmentRequest",
        "message NetsecServiceConnectAttachmentReply",
        "message ListNetsecServiceConnectAttachmentsReply",
        "message CreateNetsecNatGatewayRequest",
        "message NetsecNatGatewayReply",
        "message ListNetsecNatGatewaysReply",
        "message CreateNetsecTransitAttachmentRequest",
        "message NetsecTransitAttachmentReply",
        "message ListNetsecTransitAttachmentsReply",
        "message CreateNetsecVpnConnectionRequest",
        "message NetsecVpnConnectionReply",
        "message ListNetsecVpnConnectionsReply",
        "message CreateNetsecPeeringConnectionRequest",
        "message NetsecPeeringConnectionReply",
        "message ListNetsecPeeringConnectionsReply",
        "rpc ListServiceConnectAttachments",
        "rpc CreateServiceConnectAttachment",
        "rpc ListNatGateways",
        "rpc CreateNatGateway",
        "rpc ListTransitAttachments",
        "rpc CreateTransitAttachment",
        "rpc ListVpnConnections",
        "rpc CreateVpnConnection",
        "rpc ListPeeringConnections",
        "rpc CreatePeeringConnection",
        "map<string, string> labels = 3;",
        "repeated string allowed_private_networks = 4;",
        "optional bool enabled = 5;",
        "string mtls_cert_fingerprint = 4;",
        "map<string, string> labels = 5;",
        "repeated string allowed_private_networks = 6;",
        "repeated RegisterServiceIdentityReply items = 1;",
        "ResourceMetadata metadata = 8;",
        "string service_identity = 2;",
        "string private_route_id = 3;",
        "string service_identity_subject = 6;",
        "optional string tenant_id = 3;",
        "string public_ip = 5;",
        "optional string subnet_id = 6;",
        "optional string subnet_id = 7;",
        "repeated string route_table_ids = 7;",
        "string transit_private_network_id = 5;",
        "string transit_tenant_id = 6;",
        "string transit_cell = 7;",
        "string gateway_address = 5;",
        "repeated string remote_cidrs = 6;",
        "string routing_mode = 8;",
        "string peer_private_network_id = 5;",
        "string peer_tenant_id = 6;",
        "string peer_cell = 7;",
        "ResourceMetadata metadata = 9;",
        "ResourceMetadata metadata = 10;",
        "rpc QueryFlowAudit",
        "rpc SummarizeFlowAudit",
        "service MailService",
        "rpc CreateRelayRoute",
        "rpc CreateMessageEvent",
        "rpc DispatchMessages",
        "rpc ReplayDeadLetter",
        "rpc VerifyDomainAuth",
        "service AbuseService",
        "rpc RecordSignal",
        "rpc CreateCase",
        "rpc ReviewCase",
        "rpc CreateQuarantine",
        "rpc ReleaseQuarantine",
        "rpc CreateAppeal",
        "rpc ReviewAppeal",
        "rpc ListSupportCases",
        "rpc CreateSupportCase",
        "rpc GetSupportCase",
        "rpc TransitionSupportCase",
        "rpc EvaluateRisk",
        "service NotifyService",
        "rpc CreateWebhookEndpoint",
        "rpc CreateNotification",
        "service PolicyService",
        "rpc EvaluatePolicy",
        "message EvaluatePolicyRequest",
        "message PolicyRuleEvaluation",
        "message PolicyDecisionExplanation",
        "message EvaluatePolicyReply",
        "service GovernanceService",
        "rpc ApproveChangeRequest",
        "rpc ApplyChangeRequest",
        "rpc EvaluateRetention",
        "rpc VerifyAuditIntegrity",
        "service HaService",
        "rpc PreflightFailover",
        "service LifecycleService",
        "rpc SetMaintenance",
        "rpc VerifyIntegrity",
        "rpc Evacuate",
        "rpc UpdateRegionalQuorum",
        "rpc GetQuorumSummary",
        "service UvmService",
        "rpc ListTemplates",
        "rpc GetTemplate",
        "rpc CreateTemplate",
        "rpc ListInstances",
        "rpc GetInstance",
        "rpc CreateInstance",
        "rpc ListMigrations",
        "rpc GetMigration",
        "rpc ListSnapshots",
        "rpc GetSnapshot",
        "rpc ListOutboxMessages",
        "rpc GetOutboxMessage",
        "rpc ImportImage",
        "rpc CreateFirmwareBundle",
        "rpc ListFirmwareBundles",
        "rpc CreateGuestProfile",
        "rpc ListGuestProfiles",
        "rpc CreateOverlayPolicy",
        "rpc ListOverlayPolicies",
        "rpc RegisterNodeCapability",
        "rpc SelectAdapter",
        "rpc GetCompatibilityMatrix",
        "rpc RecordHostEvidence",
        "rpc ListHostEvidence",
        "rpc ListPreflightEvidenceArtifacts",
        "rpc CreateClaimDecision",
        "rpc ListClaimDecisions",
        "rpc CreateBenchmarkCampaign",
        "rpc ListBenchmarkCampaigns",
        "rpc CreateBenchmarkBaseline",
        "rpc ListBenchmarkBaselines",
        "rpc CreateBenchmarkResult",
        "rpc ListBenchmarkResults",
        "rpc ListRuntimeSessions",
        "rpc GetRuntimeSession",
        "rpc ListInstanceRuntimeSessions",
        "rpc GetInstanceRuntimeSession",
        "rpc RegisterRuntimeSession",
        "rpc RecordRuntimeHeartbeat",
        "rpc GetRuntimeHealth",
        "rpc PreflightRuntime",
        "rpc ListRuntimeCheckpoints",
        "rpc GetRuntimeCheckpoint",
        "rpc ListInstanceRuntimeCheckpoints",
        "rpc GetInstanceRuntimeCheckpoint",
        "rpc PreflightRuntimeMigration",
        "rpc RestoreRuntimeSession",
        "rpc CreateRuntimeCheckpoint",
        "rpc ListRuntimeMigrations",
        "rpc GetRuntimeMigration",
        "rpc StartRuntimeMigration",
        "rpc CommitRuntimeMigration",
        "rpc ListNodeOutboxMessages",
        "rpc GetNodeOutboxMessage",
        "rpc GetNativeClaimStatus",
        "rpc Reconcile",
        "message CreateUvmTemplateRequest",
        "message GetUvmTemplateRequest",
        "message UvmTemplateListRequest",
        "message UvmTemplateListReply",
        "message UvmTemplateReply",
        "message UvmPreflightEvidenceArtifactListRequest",
        "message UvmPreflightEvidenceArtifactReply",
        "message UvmPreflightEvidenceArtifactListReply",
        "message GetUvmInstanceRequest",
        "message UvmInstanceListRequest",
        "message UvmInstanceListReply",
        "message GetUvmMigrationRequest",
        "message UvmMigrationListRequest",
        "message UvmMigrationListReply",
        "message GetUvmSnapshotRequest",
        "message UvmSnapshotListRequest",
        "message UvmSnapshotListReply",
        "message GetUvmOutboxMessageRequest",
        "message UvmOutboxListRequest",
        "message UvmOutboxMessageReply",
        "message UvmOutboxListReply",
        "message ResourceMetadata",
        "map<string, string> labels = 6;",
        "optional string deleted_at = 8;",
        "message UvmFirmwareSignerLineageEntry",
        "message CreateUvmFirmwareBundleRequest",
        "message UvmFirmwareBundleReply",
        "string secure_boot_posture = 7;",
        "repeated UvmFirmwareSignerLineageEntry signer_lineage = 8;",
        "string secure_boot_posture = 9;",
        "repeated UvmFirmwareSignerLineageEntry signer_lineage = 10;",
        "uint32 policy_revision = 11;",
        "message CreateUvmGuestProfileRequest",
        "message UvmGuestProfileReply",
        "message CreateUvmOverlayPolicyRequest",
        "message UvmOverlayPolicyReply",
        "message RegisterUvmNodeCapabilityRequest",
        "message UvmNodeCapabilityReply",
        "message SelectUvmAdapterRequest",
        "message UvmAdapterSelectionReply",
        "message RecordUvmHostEvidenceRequest",
        "message UvmHostEvidenceReply",
        "message CreateUvmClaimDecisionRequest",
        "message UvmClaimDecisionReply",
        "string observed_highest_claim_tier = 16;",
        "string benchmark_claim_tier_ceiling = 17;",
        "message UvmNativeClaimStatusReply",
        "Claim-decision metadata annotations may include observed_highest_claim_tier,",
        "string observed_highest_claim_tier = 14;",
        "string benchmark_claim_tier_ceiling = 15;",
        "repeated string benchmark_ready_scenarios = 16;",
        "message CreateUvmBenchmarkCampaignRequest",
        "message UvmBenchmarkCampaignReply",
        "message CreateUvmBenchmarkBaselineRequest",
        "message UvmBenchmarkBaselineReply",
        "message CreateUvmBenchmarkResultRequest",
        "message UvmBenchmarkResultReply",
        "message GetUvmRuntimeSessionRequest",
        "message GetUvmInstanceRuntimeSessionRequest",
        "message UvmInstanceRuntimeSessionListRequest",
        "message UvmRuntimeSessionListRequest",
        "message UvmRuntimeSessionListReply",
        "message UvmRuntimeSessionReply",
        "message UvmRuntimePreflightReply",
        "message GetUvmRuntimeCheckpointRequest",
        "message GetUvmInstanceRuntimeCheckpointRequest",
        "message UvmInstanceRuntimeCheckpointListRequest",
        "message UvmRuntimeCheckpointListRequest",
        "message UvmRuntimeCheckpointListReply",
        "message UvmRuntimeCheckpointReply",
        "message GetUvmRuntimeMigrationRequest",
        "message UvmRuntimeMigrationListRequest",
        "message UvmRuntimeMigrationListReply",
        "message UvmRuntimeMigrationReply",
        "message UvmReconciliationIssue",
        "message UvmCompatibilityRequirement",
        "message UvmCompatibilityEvidence",
        "message UvmCompatibilityAssessment",
        "message UvmExecutionIntent",
        "message UvmPortabilityAssessment",
        "enum UvmPortabilityAssessmentSource",
        "enum UvmPortabilityAssessmentUnavailableReason",
        "string host_class = 12;",
        "string host_class = 19;",
        "string host_class = 11;",
        "UvmExecutionIntent execution_intent = 12;",
        "UvmExecutionIntent execution_intent = 9;",
        "UvmExecutionIntent execution_intent = 8;",
        "string cpu_topology = 14;",
        "bool apple_guest_allowed = 19;",
        "ResourceMetadata metadata = 20;",
        "optional string template_id = 16;",
        "string boot_image_id = 17;",
        "optional string host_node_id = 26;",
        "ResourceMetadata metadata = 28;",
        "optional string promoted_channel = 3;",
        "message UvmArtifactAttestationRecord",
        "reserved 19, 20;",
        "repeated UvmArtifactAttestationRecord attestations = 24;",
        "string legal_policy = 21;",
        "string signature_attestation = 9;",
        "string provenance_attestation = 10;",
        "repeated UvmArtifactAttestationRecord attestations = 12;",
        "string signature_attestation = 7;",
        "string provenance_attestation = 8;",
        "repeated UvmArtifactAttestationRecord attestations = 9;",
        "optional string preferred_backend = 1;",
        "optional string selected_backend = 4;",
        "optional string selection_reason = 6;",
        "message UvmRuntimeMigrationPreflightRequest",
        "message UvmRuntimeMigrationPreflightReply",
        "message UvmRuntimeIncarnationReply",
        "message RestoreUvmRuntimeSessionRequest",
        "UvmRuntimeIncarnationReply current_incarnation = 52;",
        "repeated UvmRuntimeIncarnationReply incarnation_lineage = 53;",
        "UvmPortabilityAssessment portability_assessment = 2;",
        "string runtime_preflight_id = 3;",
        "UvmPortabilityAssessment portability_assessment = 7;",
        "optional string runtime_preflight_id = 8;",
        "UvmPortabilityAssessmentSource portability_assessment_source = 9;",
        "optional string runtime_session_id = 10;",
        "optional UvmPortabilityAssessmentUnavailableReason portability_assessment_unavailable_reason = 11;",
        "UvmPortabilityAssessment portability_assessment = 9;",
        "UvmPortabilityAssessmentSource portability_assessment_source = 10;",
        "string runtime_preflight_id = 11;",
        "string runtime_session_id = 12;",
        "UvmPortabilityAssessmentUnavailableReason portability_assessment_unavailable_reason = 13;",
        "UVM_PORTABILITY_ASSESSMENT_SOURCE_LINKED_RUNTIME_PREFLIGHT_LINEAGE",
        "UVM_PORTABILITY_ASSESSMENT_SOURCE_RUNTIME_PREFLIGHT_FALLBACK",
        "UVM_PORTABILITY_ASSESSMENT_UNAVAILABLE_REASON_AUTHORITATIVE_RUNTIME_LINEAGE_MISSING_PORTABILITY_EVIDENCE",
        "optional uint64 last_runner_sequence_id = 54;",
        "optional string last_lifecycle_event_id = 55;",
        "optional uint64 runner_sequence_id = 8;",
        "optional string lifecycle_event_id = 9;",
        "UvmExecutionIntent execution_intent = 5;",
        "UvmPortabilityAssessment portability_assessment = 8;",
        "uint32 max_vcpu = 12;",
        "bool supports_secure_boot = 15;",
        "string workload_class = 6;",
        "string measured_at = 12;",
        "optional string note = 8;",
        "string collected_at = 9;",
        "string runtime_preflight_id = 2;",
        "string host_class_evidence_key = 5;",
        "UvmCompatibilityAssessment compatibility_assessment = 12;",
        "UvmPortabilityAssessment portability_assessment = 13;",
        "repeated string missing_required_workload_classes = 12;",
        "repeated string failing_workload_classes = 13;",
        "string decided_at = 14;",
        "optional uint32 boot_time_ms = 6;",
        "message UvmRuntimeSessionReply {\n  string id = 1;\n  string instance_id = 2;\n  string node_id = 3;",
        "message GetUvmInstanceRuntimeSessionRequest {\n  string instance_id = 1;\n  string runtime_session_id = 2;\n}",
        "message UvmInstanceRuntimeSessionListRequest {\n  string instance_id = 1;\n}",
        "repeated uint32 planned_pinned_numa_nodes = 22;",
        "string planned_migration_checkpoint_kind = 26;",
        "optional string last_heartbeat_at = 40;",
        "optional uint32 observed_pid = 42;",
        "bool migration_in_progress = 46;",
        "ResourceMetadata metadata = 51;",
        "string generated_at = 2;",
        "repeated UvmReconciliationIssue issues = 6;",
        "repeated uint32 placement_pinned_numa_nodes = 16;",
        "optional string launch_program = 19;",
        "optional uint32 migration_expected_downtime_ms = 21;",
        "string checkpoint_uri = 8;",
        "uint64 disk_generation = 10;",
        "message GetUvmInstanceRuntimeCheckpointRequest {\n  string instance_id = 1;\n  string checkpoint_id = 2;\n}",
        "message UvmInstanceRuntimeCheckpointListRequest {\n  string instance_id = 1;\n}",
        "optional string failure_detail = 10;",
        "string updated_at = 11;",
        "boot_device",
        "install_media_image_id",
        "cdrom_image",
        "compatibility_requirement",
        "compatibility_evidence",
        "compatibility_assessment",
        "execution_intent",
        "portability_assessment",
    ] {
        assert!(
            proto.contains(service),
            "protobuf snapshot missing `{service}`"
        );
    }

    for required_token in [
        "message ListIdentityUsersRequest {}",
        "message ListIdentityUsersReply",
        "message GetIdentityUserRequest",
        "message SetIdentityUserLifecycleRequest",
        "message BulkUserErrorReply",
        "message CreateSessionRequest",
        "message SessionReply",
        "message CreateApiKeyRequest",
        "message ApiKeyReply",
        "message CreateApiKeyReply",
        "message ManageApiKeyRequest",
        "message GetIdentitySummaryRequest {}",
        "message GetIdentityCredentialLifecycleRequest {}",
        "enum IdentityCredentialLifecycleKind",
        "IDENTITY_CREDENTIAL_LIFECYCLE_KIND_SESSION",
        "IDENTITY_CREDENTIAL_LIFECYCLE_KIND_API_KEY",
        "IDENTITY_CREDENTIAL_LIFECYCLE_KIND_WORKLOAD_TOKEN",
        "IDENTITY_CREDENTIAL_LIFECYCLE_KIND_SECRET_VERSION",
        "enum IdentityCredentialLifecycleState",
        "IDENTITY_CREDENTIAL_LIFECYCLE_STATE_ACTIVE",
        "IDENTITY_CREDENTIAL_LIFECYCLE_STATE_EXPIRING",
        "IDENTITY_CREDENTIAL_LIFECYCLE_STATE_EXPIRED",
        "IDENTITY_CREDENTIAL_LIFECYCLE_STATE_INACTIVE",
        "IDENTITY_CREDENTIAL_LIFECYCLE_STATE_REVOKED",
        "IDENTITY_CREDENTIAL_LIFECYCLE_STATE_SUSPENDED_OWNER",
        "enum IdentityCredentialSecretSourceKind",
        "message IdentityCredentialLifecycleEntryReply",
        "optional IdentityCredentialSecretSourceKind source_kind = 9;",
        "message IdentityCredentialLifecycleReportReply",
        "message IdentitySummaryReply",
        "rpc ListUsers",
        "rpc GetUser",
        "rpc SuspendUser",
        "rpc ReactivateUser",
        "rpc CreateSession",
        "rpc CreateApiKey",
        "rpc RotateApiKey",
        "rpc RevokeApiKey",
        "rpc GetIdentitySummary",
        "rpc GetIdentityCredentialLifecycle",
        "message WorkloadCredentialReply",
        "WorkloadCredentialReply credential = 10;",
        "message ManageWorkloadIdentityRequest",
        "rpc RotateWorkloadIdentity",
        "rpc RevokeWorkloadIdentity",
        "enum SecretRevealGrantKind",
        "SECRET_REVEAL_GRANT_KIND_APPROVAL",
        "SECRET_REVEAL_GRANT_KIND_LEASE",
        "message SecretRevealGrantReply",
        "SecretRevealGrantKind grant_kind = 3;",
        "optional string expires_at = 8;",
        "uint32 reveal_count = 9;",
        "message ApproveSecretRevealRequest",
        "message IssueSecretRevealLeaseRequest",
        "uint32 lease_seconds = 3;",
        "message RevealSecretWithGrantRequest",
        "string grant_id = 2;",
        "message SecretRevealReply",
        "service SecretsService",
        "rpc ApproveSecretReveal",
        "rpc IssueSecretRevealLease",
        "rpc RevealSecretWithGrant",
        "enum BudgetPeriod",
        "BUDGET_PERIOD_MONTHLY",
        "BUDGET_PERIOD_QUARTERLY",
        "BUDGET_PERIOD_ANNUAL",
        "BUDGET_PERIOD_CUSTOM",
        "enum SpendCapBehavior",
        "SPEND_CAP_BEHAVIOR_SOFT",
        "SPEND_CAP_BEHAVIOR_HARD",
        "enum BudgetNotificationKind",
        "BUDGET_NOTIFICATION_KIND_THRESHOLD_REACHED",
        "BUDGET_NOTIFICATION_KIND_SOFT_CAP_EXCEEDED",
        "BUDGET_NOTIFICATION_KIND_HARD_CAP_BLOCKED",
        "enum SupportTier",
        "SUPPORT_TIER_STANDARD",
        "SUPPORT_TIER_BUSINESS",
        "SUPPORT_TIER_ENTERPRISE",
        "SUPPORT_TIER_CUSTOM",
        "enum SupportEntitlementSourceKind",
        "SUPPORT_ENTITLEMENT_SOURCE_KIND_BILLING_ACCOUNT",
        "SUPPORT_ENTITLEMENT_SOURCE_KIND_SUBSCRIPTION",
        "message GetBillingSummaryRequest {}",
        "message ListBillingSupportEntitlementsRequest {}",
        "message SupportEntitlementReply",
        "optional string subscription_id = 3;",
        "SupportEntitlementSourceKind source_kind = 4;",
        "SupportTier support_tier = 6;",
        "repeated string channels = 7;",
        "uint32 initial_response_sla_minutes = 8;",
        "message ListBillingSupportEntitlementsReply",
        "message ListBillingBudgetsRequest {}",
        "message CreateBillingBudgetRequest",
        "message BudgetReply",
        "message ListBillingBudgetsReply",
        "message ListBudgetBurnRecordsRequest {}",
        "message BudgetBurnReply",
        "message ListBudgetBurnRecordsReply",
        "message ListBudgetNotificationsRequest {}",
        "message BudgetNotificationReply",
        "message ListBudgetNotificationsReply",
        "message GetBillingOwnerSummariesRequest {}",
        "message BillingOwnerSummaryReply",
        "message BillingOwnerSummariesReply",
        "message BillingSummaryReply",
        "uint32 support_entitlement_count = 11;",
        "map<string, uint32> budget_notification_kind_totals = 23;",
        "uint32 support_entitlement_count = 27;",
        "uint32 active_support_entitlement_count = 28;",
        "uint32 support_entitlements_linked_to_active_accounts = 29;",
        "uint32 support_entitlements_linked_to_active_subscriptions = 30;",
        "map<string, uint32> support_entitlement_source_totals = 31;",
        "map<string, uint32> support_tier_totals = 32;",
        "message CreateRemediationCaseRequest",
        "message RemediationWorkflowStepReply",
        "message RemediationCaseReply",
        "repeated RemediationWorkflowStepReply workflow_steps = 3;",
        "repeated string rollback_evidence_refs = 12;",
        "message ListRemediationCasesRequest",
        "optional string evidence_state = 3;",
        "optional string escalation_state = 5;",
        "message ListRemediationCasesReply",
        "message GetRemediationCaseRequest",
        "message EscalateRemediationCaseRequest",
        "rpc ListRemediationCases",
        "rpc CreateRemediationCase",
        "rpc GetRemediationCase",
        "rpc EscalateRemediationCase",
        "message CreateSupportCaseRequest",
        "message SupportCaseReply",
        "optional string owner = 4;",
        "repeated string remediation_case_ids = 8;",
        "repeated string change_request_ids = 9;",
        "repeated string notify_message_ids = 10;",
        "message ListSupportCasesRequest",
        "message ListSupportCasesReply",
        "message GetSupportCaseRequest",
        "message TransitionSupportCaseRequest {\n  string support_case_id = 1;\n  string reason = 2;\n  optional string status = 3;\n  optional string owner = 4;\n}",
        "message ListBillingProviderSyncTasksRequest {}",
        "message ProviderSyncTaskReply",
        "string payload_json = 5;",
        "message ListBillingProviderSyncTasksReply",
        "message MarkBillingProviderSyncDeliveredRequest",
        "service BillingService",
        "rpc GetBillingSummary",
        "rpc ListSupportEntitlements",
        "rpc ListBudgets",
        "rpc CreateBudget",
        "rpc ListBudgetBurnRecords",
        "rpc ListBudgetNotifications",
        "rpc GetBillingOwnerSummaries",
        "rpc ListProviderSyncTasks",
        "rpc MarkProviderSyncDelivered",
        "message NotifyWebhookEndpointReply",
        "message ListNotifyWebhookEndpointsRequest {}",
        "message ListNotifyWebhookEndpointsReply",
        "message RotateNotifyWebhookSecretRequest",
        "message NotificationTemplateReply",
        "message ListNotificationTemplatesRequest {}",
        "message ListNotificationTemplatesReply",
        "message NotificationPreferenceReply",
        "message ListNotificationPreferencesRequest {}",
        "message ListNotificationPreferencesReply",
        "message CreateNotifyAlertRouteRequest",
        "message NotifyAlertRouteReply",
        "message ListNotifyAlertRoutesRequest {}",
        "message ListNotifyAlertRoutesReply",
        "message TriggerNotifyAlertRequest",
        "message TriggerNotifyAlertReply",
        "message CreateNotificationRequest {\n  string channel = 1;\n  string destination = 2;\n  string subject = 3;\n  string body = 4;\n  optional string template_id = 5;\n  map<string, string> template_vars = 6;\n  optional string subject_key = 7;\n  optional string locale = 8;\n  optional string webhook_endpoint_id = 9;\n  optional uint32 max_attempts = 10;\n  optional uint32 deliver_after_seconds = 11;\n  optional string case_reference = 12;\n}",
        "message ListNotificationsRequest {}",
        "message NotificationHistoryEntryReply",
        "optional string case_reference = 8;",
        "optional string related_notification_id = 9;",
        "message NotificationReply",
        "optional string acknowledged_at = 16;",
        "optional string acknowledged_by = 17;",
        "optional string acknowledgement_note = 18;",
        "optional string snoozed_until = 19;",
        "optional string snoozed_by = 20;",
        "optional string snooze_reason = 21;",
        "optional string last_escalated_at = 23;",
        "optional string last_escalated_by = 24;",
        "optional string last_escalated_notification_id = 25;",
        "optional string case_reference = 30;",
        "message ListNotificationsReply",
        "message GetNotifySummaryRequest {}",
        "message NotifySummaryReply",
        "message GetNotificationHistoryRequest",
        "message NotificationHistoryReply {\n  string notification_id = 1;\n  optional string case_reference = 2;\n  optional string acknowledged_at = 3;\n  optional string acknowledged_by = 4;\n  optional string snoozed_until = 5;\n  uint32 escalation_count = 6;\n  optional string last_escalated_notification_id = 7;\n  repeated NotificationHistoryEntryReply history = 8;\n}",
        "message DeliverNotificationRequest",
        "message AcknowledgeNotificationRequest {\n  string notification_id = 1;\n  optional string note = 2;\n  optional string case_reference = 3;\n}",
        "message SnoozeNotificationRequest {\n  string notification_id = 1;\n  optional uint32 snooze_seconds = 2;\n  optional string reason = 3;\n  optional string case_reference = 4;\n}",
        "message EscalateNotificationRequest {\n  string notification_id = 1;\n  string channel = 2;\n  string destination = 3;\n  optional string subject = 4;\n  optional string body = 5;\n  optional string subject_key = 6;\n  optional string case_reference = 7;\n  optional string locale = 8;\n  optional string webhook_endpoint_id = 9;\n  optional uint32 max_attempts = 10;\n  optional uint32 deliver_after_seconds = 11;\n  optional string reason = 12;\n}",
        "message RetryNotificationRequest",
        "message NotificationDeadLetterReply",
        "message ListNotificationDeadLettersReply",
        "message ListNotifyOutboxRequest {}",
        "message NotifyOutboxMessageReply",
        "message ListNotifyOutboxReply",
        "service NotifyService",
        "rpc ListWebhookEndpoints",
        "rpc RotateWebhookSecret",
        "rpc ListTemplates",
        "rpc ListPreferences",
        "rpc ListAlertRoutes",
        "rpc CreateAlertRoute",
        "rpc TriggerAlert",
        "rpc GetNotifySummary",
        "rpc ListNotifications",
        "rpc GetNotificationHistory",
        "rpc DeliverNotification",
        "rpc AcknowledgeNotification",
        "rpc SnoozeNotification",
        "rpc EscalateNotification",
        "rpc ListDeadLetters",
        "rpc RetryNotification",
        "rpc ListOutbox",
    ] {
        assert!(
            proto.contains(required_token),
            "protobuf snapshot missing `{required_token}`"
        );
    }
}

#[test]
fn typed_id_snapshot_contains_private_connectivity_ids() {
    let root = workspace_root();
    let ids = fs::read_to_string(root.join("crates/uhost-types/src/id.rs"))
        .unwrap_or_else(|error| panic!("failed to read typed id definitions: {error}"));

    for required_token in [
        "define_id!(NatGatewayId, \"nat\");",
        "define_id!(TransitAttachmentId, \"trn\");",
        "define_id!(VpnConnectionId, \"vpn\");",
        "define_id!(PeeringConnectionId, \"peer\");",
        "define_id!(ServiceIdentityId, \"sid\");",
        "define_id!(ServiceConnectAttachmentId, \"sca\");",
    ] {
        assert!(
            ids.contains(required_token),
            "typed id snapshot missing token {required_token}"
        );
    }
}
